### PR TITLE
Implemented server side data rendering on datatable

### PR DESCRIPTION
**Pull request by axnish27**
the function is already there , made some changes to the table columns names

### CODE REVIEW

**Comment by Raza9798** [comment]
> the function is already there , made some changes to the table columns names

please use ajax request to pull the data instead of axios response @axnish27

**Comment by axnish27** [comment]
implemented please check

**Comment by Raza9798** [comment]
> implemented please check @Raza9798

Please mention the PR links in the comments here after

**Comment by axnish27** [comment]
okay sure

**Pull request merged**
