### PR TITLE
Make forget password/reset feature

### PR DESCRIPTION
**Pull request by aanish27**
#121 Implemented please review @Raza9798

### CODE REVIEW

**Review by Raza9798 — CHANGES_REQUESTED** [review]
image

**Comment by aanish27** [comment]
Fixed above issue on sign up

**Review by Raza9798 — CHANGES_REQUESTED** [review]
Overwrite the default email with a custom one make a new template

**Comment by aanish27** [comment]
> Overwrite the default email with a custom one make a new template

Implemented please review again @Raza9798  #121

**Review by Raza9798 — CHANGES_REQUESTED** [review]
On this PR you have mixed, Notification Class with Mailing feature. what I requested was make a mail feature. it should extends Mail class instead of notification Class. Please remove the notification handlers and integrated mailable feature.

**Comment by aanish27** [comment]
> On this PR you have mixed, Notification Class with Mailing feature. what I requested was make a mail feature. it should extends Mail class instead of notification Class. Please remove the notification handlers and integrated mailable feature.

Yes...the thing was i couldn't find proper resources to to implement this feature using mailable.....they are using a notification so i just override that according to the documentation...
https://laravel.com/docs/11.x/passwords#password-customization

im using larval breeze so i have to intercept the notification it sending and override with mailable...can you point out some resources to refer...

**Comment by Raza9798** [comment]
> > On this PR you have mixed, Notification Class with Mailing feature. what I requested was make a mail feature. it should extends Mail class instead of notification Class. Please remove the notification handlers and integrated mailable feature.
> 
> Yes...the thing was i couldn't find proper resources to to implement this feature using mailable.....they are using a notification so i just override that according to the documentation... https://laravel.com/docs/11.x/passwords#password-customization
> 
> im using larval breeze so i have to intercept the notification it sending and override with mailable...can you point out some resources to refer...

https://laravel.com/docs/11.x/mail

**Comment by aanish27** [comment]
Removed notifications and implemented using mailable @Raza9798 #121 

image

**Review by Raza9798 — APPROVED** [review]

**Pull request merged**
